default_platform(:ios)

platform :ios do
  desc "Build and upload a build to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: ENV["ASC_KEY_FILEPATH"],
      in_house: false
    )

    build_number = ENV["BUILD_NUMBER"] || Time.now.strftime("%Y%m%d%H%M")

    build_app(
      project: "DecisionDeck.xcodeproj",
      scheme: "DecisionDeck",
      export_method: "app-store",
      xcargs: "CURRENT_PROJECT_VERSION=#{build_number}",
      export_options: {
        provisioningProfiles: {
          "com.hdeazy.selectless" => ENV["PROVISIONING_PROFILE_NAME"]
        }
      }
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
